axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$', views.home, name='index'),  # 首页
    url(r'^home/$', views.home, name='home'),   # 首页
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的
]

project_AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf')),
]

axf/models.py
from django.db import models

# Create your models here.
class Base(models.Model):
    img = models.CharField(max_length=520)
    name = models.CharField(max_length=250)
    trackid = models.CharField(max_length=10)
    class Meta:
        abstract=True

#轮播图
class Lunbo(Base):
    class Meta:
        db_table='axf_wheel'

#导航
class Nav(Base):
    class Meta:
        db_table='axf_nav'

#每日必购
class Mustbuy(Base):
    class Meta:
        db_table='axf_mustbuy'

#商品部分
class Shop(Base):
    class Meta:
        db_table='axf_shop'

#首页主体部分
class MainShow(models.Model):
    trackid = models.CharField(max_length=8)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=8)
    brandname = models.CharField(max_length=50)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=8)
    productid1 = models.CharField(max_length=8)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField()
    marketprice1 = models.FloatField()

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=8)
    productid2 = models.CharField(max_length=8)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField()
    marketprice2 = models.FloatField()

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=8)
    productid3 = models.CharField(max_length=8)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField()
    marketprice3 = models.FloatField()

    class Meta:
        db_table = 'axf_mainshow'

#闪购超市　商品侧边分类
class Foodtypes(models.Model):
    typeid = models.CharField(max_length=8) # 分类ID
    typename = models.CharField(max_length=100) # 分类名称
    childtypenames = models.CharField(max_length=256)   # 子类名称
    typesort = models.IntegerField()    # 显示先后顺序
    class Meta:
        db_table = 'axf_foodtypes'


#闪购超市　商品数据
class Goods(models.Model):
    productid = models.CharField(max_length=10) # 商品ID
    productimg = models.CharField(max_length=100)   # 商品图片
    productname = models.CharField(max_length=100)  # 商品名称
    productlongname = models.CharField(max_length=100)  # 商品弄名称
    isxf = models.BooleanField(default=False)    # 精选
    pmdesc = models.BooleanField(default=False)  # 买一送一
    specifics = models.CharField(max_length=100)   # 规格
    price = models.DecimalField(max_digits=7, decimal_places=2)    # 价格
    marketprice = models.DecimalField(max_digits=7, decimal_places=2)  # 商场价格
    categoryid= models.IntegerField()   # 分类ID
    childcid = models.IntegerField()    # 子类ID
    childcidname = models.CharField(max_length=100) # 分类名称
    dealerid = models.CharField(max_length=10)  # 详情ID
    storenums = models.IntegerField()   # 库存
    productnum = models.IntegerField()  # 销量

    class Meta:
        db_table = 'axf_goods'

axf/views.py
from django.shortcuts import render

# Create your views here.
from axf.models import Lunbo, Nav, Mustbuy, Shop, MainShow, Foodtypes, Goods


def home(request):

    #轮播图
    wheels = Lunbo.objects.all()

    #导航
    navs = Nav.objects.all()

    #每日必购
    mustbuy = Mustbuy.objects.all()

    #商品部分
    shop = Shop.objects.all()

    shoptab = shop[1:3]
    shopclass = shop[3:7]
    shopcommend = shop[7:11]

    #首页主体部分
    mainshow = MainShow.objects.all()



    data = {
        'wheels':wheels,
        'navs':navs,
        'mustbuys':mustbuy,
        'shops':shop,
        'shoptabs':shoptab,
        'shopclass':shopclass,
        'shopcommends':shopcommend,
        'mainshows':mainshow,


    }



    return render(request,'home/home.html',context=data)


def market(request,categoryid,childid,sortid):
    # 　闪购超市　商品侧边分类
    foodtypes = Foodtypes.objects.all()

    #当在闪购超市页面点击分类侧边栏时，能显示对应的分类商品；但当点击首页
    #再次回到闪购超市页面时，显示的不是你刚点击的分类的商品，而是打开闪购超市页面
    # 默认显示第一栏热销榜的商品(在base.html中设置了默认参数)，这是因为用cookie
    #获取到的typeIndex并未与商品进行关联；
    #所以需要在这里获取到cookie保存的typeIndex来与商品id进行关联

    #这里需要给个默认下标值，因为进入闪购超市时，还未点击，cookie也就没有值，
    #刚进入时让其默认显示第一栏，所以这里需要给个默认下标值０
    #注意数据类型，获取到的值都是字符串类型，所以用int转换为数字类型
    typeIndex = int(request.COOKIES.get('typeIndex',0))

    #商品id(typeid)在模型类Foodtypes里面
    #点击哪个分类时，cookie获取到分类下标，通过这个下标取到具体点击的一个商品，获取这个商品的分类id
    #这就将typeIndex与typeid关联起来了
    categoryid = foodtypes[typeIndex].typeid



    #顶部导航栏，子类信息
    #childtypenames:全部分类:0#进口水果:103534#国产水果:103533
    childtypenames = foodtypes.get(typeid=categoryid).childtypenames

    #将每个子类拆分出来
    childtypeList = []
    for item in childtypenames.split("#"):
        list1 = item.split(":")
        dict1 = {
            'childname':list1[0],   #子类名称  全部分类   进口水果  国产水果
            'childid':list1[1]      #子类id    0        103534   103533

        }
        childtypeList.append(dict1)

    # 通过点击分类侧边栏，a标签的路由指向market，并在后面带参分类id（typeid），这个分类id
    # 在foodtype里面，然后传到url，url再把参数传到对应视图函数，这个categoryid
    # 接收传过来的typeid，然后根据这个id来过滤商品
    # 商品信息(过滤根据分类id)


    #顶部导航左边分类
    #如果传了子类id,则根据子类id进一步过滤，如果没点击子类a标签，则没传子类id，所以需要给个默认值０，默认显示全部分类
    #这个０要设置在base.html中的market路由里
    # 注意侧边栏a标签的路由分类id后面也要给个默认子类id参数0
    if childid=="0":       #说明只显示侧边栏大分类
        goods = Goods.objects.filter(categoryid=categoryid)
    else:                  #说明点击了顶部导航栏里的子类a标签
        goods = Goods.objects.filter(categoryid=categoryid,childcid=childid)


    #顶部导航右边排序
    if sortid == '1':  # 销量排序
        goods = goods.order_by('-productnum')
    elif sortid == '2':  # 价格最低
        goods = goods.order_by('price')
    elif sortid == '3':  # 价格最高
        goods = goods.order_by(('-price'))





    data = {
        'foodtypes':foodtypes,
        'goods':goods,
        'childtypeList':childtypeList,
        'categoryid':categoryid,
        'childid':childid,

    }


    return render(request,'market/market.html',context=data)


def cart(request):
    return render(request,'cart/cart.html')


def mine(request):
    return render(request,'mine/mine.html')

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {#  CSS#}
    {% block extcss %}
    {% endblock %}

    <title>
        {#      标题#}
        {% block title %}
        {% endblock %}
    </title>
</head>


<body>
{# 头部#}
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}

{# 主体内容#}
<div class="hidescroll">
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</div>

{# 尾部#}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' 104749 0 0 %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购超市</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>


{% endblock %}

</body>


<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{# JS#}
{% block extjs %}
{% endblock %}

</html>

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block title %}
    爱鲜蜂 | 购物车
{% endblock %}

{% block content %}
    购物车
{% endblock %}

templates/home/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 首页
{% endblock %}

{% block content %}
    <div class="home">
        {#    轮播图#}
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for wheel in wheels %}
                    <div class="swiper-slide">
                        <img src="{{ wheel.img }}" alt="">
                    </div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
            <!-- Add Arrows -->
            {#            <div class="swiper-button-next"></div>#}
            {#            <div class="swiper-button-prev"></div>#}
        </div>
        {#    导航#}
        <div class="nav">
            <ul>
                {% for nav in navs %}
                    <li>
                        <img src="{{ nav.img }}" alt="">
                        <span>{{ nav.name }}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {#    每日必购#}
        <div class="swiper-container" id="mustbuySwiper">
            <div class="swiper-wrapper">
                {% for mustbuy in mustbuys %}
                    <div class="swiper-slide">
                        <img src="{{ mustbuy.img }}" alt="">
                    </div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            {#            <div class="swiper-pagination"></div>#}
        </div>
        {#    商品部分#}
        <div class="shop">
            <div class="shophead">
                <a href="#">
                    <img src="{{ shops.first.img }}" alt="">
                </a>
            </div>
            <div class="shoptab">
                {% for shoptab in shoptabs %}
                    <a href="#">
                        <img src="{{ shoptab.img }}" alt="">
                    </a>
                {% endfor %}
            </div>
            <div class="shopclass">
                {% for shoplone in shopclass %}
                    <li>
                        <a href="#">
                            <img src="{{ shoplone.img }}" alt="">
                        </a>
                    </li>
                {% endfor %}
            </div>
            <div class="shopcommend">
                {% for shopcommend in shopcommends %}
                    <li>
                        <a href="">
                            <img src="{{ shopcommend.img }}" alt="">
                        </a>
                    </li>
                {% endfor %}
            </div>
        </div>
        {#    主体部分 #}
        <div class="main">
            {% for mainshow in mainshows %}
                <div class="main-wrapper">
                    <div class="title">
                        {{ mainshow.name }}
                        <a href="#">
                            更多
                        </a>
                        <span></span>
                    </div>
                    <div class="headimg">
                        <img src="{{ mainshow.img }}" alt="">
                    </div>
                    <div class="shoplist">
                        <div class="shopitem">
                            <a href="#">
                                <img src="{{ mainshow.img1 }}" alt="" class="img">
                                <span class="desc">{{ mainshow.longname1 }}</span>
                                <span class="price">{{ mainshow.price1 }}</span>
                                <span class="marketprice">{{ mainshow.marketprice1 }}</span>
                            </a>
                            <button><span>+</span></button>
                        </div>
                        <div class="shopitem">
                            <a href="#">
                                <img src="{{ mainshow.img2 }}" alt="" class="img">
                                <span class="desc">{{ mainshow.longname2 }}</span>
                                <span class="price">{{ mainshow.price2 }}</span>
                                <span class="marketprice">{{ mainshow.marketprice2 }}</span>
                            </a>
                            <button><span>+</span></button>
                        </div>
                        <div class="shopitem">
                            <a href="#">
                                <img src="{{ mainshow.img3 }}" alt="" class="img">
                                <span class="desc">{{ mainshow.longname3 }}</span>
                                <span class="price">{{ mainshow.price3 }}</span>
                                <span class="marketprice">{{ mainshow.marketprice3 }}</span>
                            </a>
                            <button><span>+</span></button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block title %}
    爱鲜蜂 | 闪购超市
{% endblock %}

{% block content %}
    <div class="market">
        <div class="type-slider">
            <ul>
                {% for foodtype in foodtypes %}
                    <li class="type_item">
                        <span></span> {#  #}
                        <a href="{% url 'axf:market' foodtype.typeid 0 0 %}">
                            {{ foodtype.typename }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <nav>
            <ul>
                <li id="left_top">
                    <span>
                        全部类型
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </span>
                </li>
                <li id="right_top">
                    <span>
                        综合排序
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </span>
                </li>
            </ul>
        </nav>
        <div class="main-content">
            <div class="content-wrapper">
                <ul>
                    {% for good in goods %}
                        <li>
                            <a href="#">
                                <img src="{{ good.productimg }}" alt="" class="goods-img">
                                <div class="goods-info">
                                    <p class="name">{{ good.productlongname }}</p>
                                    <p class="detailtag">
                                        {% if good.isxf %}
                                            <i class="xf">精选</i>
                                        {% endif %}
                                    </p>
                                    <p class="specifics">
                                        {{ good.specifics }}
                                    </p>
                                    <p class="price">
                                        <span class="now-price">{{ good.price }}</span>
                                        <span class="market-price">{{ good.marketprice }}</span>
                                    </p>
                                </div>
                            </a>
                            <div class="bt-wrapper">
                                <span class="glyphicon glyphicon-minus-sign"></span>
                                <span class="num">6</span>
                                <span class="glyphicon glyphicon-plus-sign"></span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            {#  分类中子类 #}
            {#  全部类型#}
            <div class="bounce-view type-view">
                <div class="bounce-wrapper">
                    {% for child in childtypeList %}
                        <a href="{% url 'axf:market' categoryid child.childid 0 %}">
                            {{ child.childname }}
                        </a>
                    {% endfor %}
                </div>
            </div>

            {#   综合排序#}
            <div class="bounce-view sort-view">
                <div class="bounce-wrapper">
                    <a href="{% url 'axf:market' categoryid childid 0  %}">综合排序</a>
                    <a href="{% url 'axf:market' categoryid childid 1  %}">销量排序</a>
                    <a href="{% url 'axf:market' categoryid childid 2  %}">价格最低</a>
                    <a href="{% url 'axf:market' categoryid childid 3  %}">价格最高</a>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

{% block extjs %}
    <script src="{% static  'market/js/market.js' %}"></script>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block title %}
    爱鲜蜂 | 我的
{% endblock %}

{% block content %}
    我的
{% endblock %}